config/routes.rb
Makerbook::Application.routes.draw do

  root 'students#show_all'
  get '/students' => 'students#show_all'
  get '/students/:student_name', to: 'students#show', as: 'student'

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	
	def show
		first_name = params[:student_name]
    @student = Student.find_by_first_name(first_name)
	end

	def show_all
		@students = Student.all
	end

end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Makerbook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/show.html.erb
<p><%= @student.first_name %> <%= @student.last_name %></p>
<img src="<%= @student.photo%>">

<p><%= link_to 'home', root_path %></p>

app/views/students/show_all.html.erb
<h2> Gentle Students</h2>
<ul>
  <% @students.each do |student| %>
    <li><%= link_to student.full_name, student_path(student.first_name) %></li>
   
  <% end %>
</ul>	